redisio:
  restart: always
  image: redis:latest
postgresql:
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_HOST_AUTH_METHOD: "trust"
multistreamer:
  restart: always
  image: jprjr/multistreamer:12.3.0-1
  links:
   - redisio
   - postgresql

